server:
  port: 9870

jwt:
  secret: smartshop

spring:
  #  boot:
  #    admin: #https://codecentric.github.io/spring-boot-admin/2.1.6/
  #      client:
  #        enabled: true
  #        url: localhost:9871
  #        username: admin
  #        password: admin

  application:
    name: 'smart_shop'
    admin:
      enabled: true

  banner:
    charset: 'UTF-8'

  # https://stackoverflow.com/questions/35347269/javax-mail-authenticationfailedexception-535-5-7-8-username-and-password-not-ac
  mail:
    default-encoding: 'UTF-8'
    host: 'smtp.gmail.com'
    port: 587
    username: 'luffylsbrucelee96@gmail.com'
    password: 'hoanghuynh0801'
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true

  #  security:

  data:
    rest:
      base-path: 'smart_shop'

  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.0.100:1521:xe
    username: truongbb
    password: 123456
    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1 FROM DUAL

  jpa:
    show-sql: true

  http:
    encoding:
      charset: UTF-8
      enabled: true
