server:
  port: 9870

jwt:
  secret: smartshop

spring:
  application:
    name: 'smart_shop'
    admin:
      enabled: true

  banner:
    charset: 'UTF-8'

#  mail:
#    default-encoding: 'UTF-8'
#    host: 'smtp.example.com'
#    port: 0000
#    username: ''
#    password: ''
#
#  security:

  data:
    rest:
      base-path: 'smart_shop'

  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.0.100:1521:xe
    username: truongbb
    password: 123456
    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1 FROM DUAL

  jpa:
    show-sql: true

  http:
    encoding:
      charset: UTF-8
      enabled: true
