-- CREATE
CREATE SEQUENCE ROLE_SEQ;
CREATE SEQUENCE USER_SEQ;
CREATE SEQUENCE GENDER_SEQ;
CREATE SEQUENCE PERSON_SEQ;
CREATE SEQUENCE CUSTOMER_TYPE_SEQ;
CREATE SEQUENCE SHIP_ADDRESS_SEQ;
CREATE SEQUENCE CUSTOMER_SEQ;


CREATE SEQUENCE SALARY_SEQ;
CREATE SEQUENCE POSITION_SEQ;
CREATE SEQUENCE ETHNIC_SEQ;
CREATE SEQUENCE LITERACY_SEQ;
CREATE SEQUENCE DEPARTMENT_SEQ;
CREATE SEQUENCE EMPLOYEE_SEQ;


CREATE SEQUENCE PRODUCT_CATEGORY_SEQ;
CREATE SEQUENCE DISCOUNT_SEQ;
CREATE SEQUENCE WAREHOUSE_SEQ;
CREATE SEQUENCE PRODUCT_SEQ;

CREATE SEQUENCE AUTHOR_SEQ;
CREATE SEQUENCE PUBLISHER_SEQ;
CREATE SEQUENCE BOOK_CATEGORY_SEQ;
CREATE SEQUENCE BOOK_SEQ;


CREATE SEQUENCE PURCHASE_METHOD_SEQ;
CREATE SEQUENCE ORDERS_SEQ;
CREATE SEQUENCE ORDER_PRODUCT_SEQ;

/*
 *=======================================================
 */

-- DROP
DROP SEQUENCE ROLE_SEQ;
DROP SEQUENCE USER_SEQ;
DROP SEQUENCE GENDER_SEQ;
DROP SEQUENCE PERSON_SEQ;
DROP SEQUENCE CUSTOMER_TYPE_SEQ;
DROP SEQUENCE SHIP_ADDRESS_SEQ;
DROP SEQUENCE CUSTOMER_SEQ;


DROP SEQUENCE SALARY_SEQ;
DROP SEQUENCE POSITION_SEQ;
DROP SEQUENCE ETHNIC_SEQ;
DROP SEQUENCE LITERACY_SEQ;
DROP SEQUENCE DEPARTMENT_SEQ;
DROP SEQUENCE EMPLOYEE_SEQ;


DROP SEQUENCE PRODUCT_CATEGORY_SEQ;
DROP SEQUENCE DISCOUNT_SEQ;
DROP SEQUENCE WAREHOUSE_SEQ;
DROP SEQUENCE PRODUCT_SEQ;

DROP SEQUENCE AUTHOR_SEQ;
DROP SEQUENCE PUBLISHER_SEQ;
DROP SEQUENCE BOOK_CATEGORY_SEQ;
DROP SEQUENCE BOOK_SEQ;


DROP SEQUENCE PURCHASE_METHOD_SEQ;
DROP SEQUENCE ORDERS_SEQ;
DROP SEQUENCE ORDER_PRODUCT_SEQ;
